package fil.coo.answer;

import fil.coo.answer.graphical.*;

/**
 * Generic class who represents an Answer
 * It's characterized by :
 * 
 * - The correct Answer
 * Type will be generated by subclasses
 *
 * @author DEROISSART Maxime | SASU Daniel
 *
 */

public abstract class Answer<T> {
	
	
	
	//ATTRIBUTE
	
	protected T correctAnswer;

	//CONSTRUCTOR
	
		public Answer (T correctAnswer)
		{
			this.correctAnswer = correctAnswer;
		}
	
	/**
	 * Returns correctAnswer
	 * @return correctAnswer
	 */
	public T getCorrectAnswer()
	{
		return correctAnswer;
	}
	
	//ABSTRACT METHODS
	
	
	/**
	 * Returns <code>true</code> if the <code>userAnswer</code> is correct
	 * @param userAnswer an answer provided by the user, the <code>userAnswer</code>
	 * 		  will be compared with the 'correct' answer. 
	 * @return <code>true</code> if the <code>userAnswer</code> is correct
	 */
	public abstract boolean isCorrectAnswer(String userAnswer);


	/**
	 * Returns the type of the answer
	 * @return the type of the answer
	 */
	public abstract String getTypeOfAnswer();
	
	
	
	/**
	 * Returns <code>true</code> if <code>userAnswer</code> has the same type 
	 * as the correct answer
	 * @param userAnswer an answer provided by the user, the <code>userAnswer</code>'s type
	 * 		  will be compared with the 'correct' answer's type. 
	 * @return <code>true</code> if <code>userAnswer</code> has the same type 
	 */
	public abstract boolean isValidTypeOfAnswer(String userAnswer);
	
	/**
	 * Creates an Answer Panel. It'll be used in the GUI version
	 * @return an Answer Panel
	 */
	public abstract AnswerPanel createMyAnswerPanel();

}
